# Generated by Django 5.0 on 2023-12-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Registrado", "REGISTRADO"),
                            ("En Progreso", "EN PROGRESO"),
                            ("Culminado", "CULMINADO"),
                            ("Cancelado", "CANCELADO"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Prioridad Media", "PRIORIDAD MEDIA"),
                            ("Prioridad Baja", "PRIORIDAD BAJA"),
                            ("Prioridad Alta", "PRIORIDAD ALTA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_final", models.DateField()),
            ],
        ),
    ]
