# Generated by Django 5.0 on 2023-12-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Prioridad Media", "PRIORIDAD MEDIA"),
                    ("Prioridad Baja", "PRIORIDAD BAJA"),
                    ("Prioridad Alta", "PRIORIDAD ALTA"),
                ],
                default="Prioridad Media",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registrado", "REGISTRADO"),
                    ("En Progreso", "EN PROGRESO"),
                    ("Culminado", "CULMINADO"),
                    ("Cancelado", "CANCELADO"),
                ],
                default="Registrado",
                max_length=20,
            ),
        ),
    ]
