# Generated by Django 4.2.2 on 2023-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0002_alter_task_description_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="priority",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registrado", "REGISTRADO"),
                    ("Culminado", "CULMINADO"),
                    ("Cancelado", "CANCELADO"),
                ],
                default="Registrado",
                max_length=20,
            ),
        ),
    ]
