# Generated by Django 4.2.2 on 2023-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0003_remove_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_final",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registrado", "REGISTRADO"),
                    ("Culminado", "CULMINADO"),
                    ("Pausado", "PAUSADO"),
                ],
                default="Registrado",
                max_length=20,
            ),
        ),
    ]
