# Generated by Django 4.2.2 on 2023-12-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0004_alter_task_date_final_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registrado", "Registrado"),
                    ("Culminado", "Culminado"),
                    ("Pausado", "Pausado"),
                ],
                default="Registrado",
                max_length=20,
            ),
        ),
    ]
